version: "3.4"

services:
  app:
    image: ${DOCKER_REGISTRY-}google-servless
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/app
    ports:
      - "8000:8000"
